using Godot;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

public static class FileUtil
{
    public static string Name { get; set; } = nameof(FileUtil);
    /// <summary>
    /// 将指定路径的ZIP文件解压到与其同名的文件夹中。
    /// </summary>
    /// <param name="zipPath">ZIP文件的完整路径，例如 "user://data.zip"</param>
    public static void UnzipFile(string zipPath)
    {
        var zipReader = new ZipReader();
        Error error = zipReader.Open(zipPath);

        if (error != Error.Ok)
        {
            GD.PrintErr($"无法打开ZIP文件: {zipPath}, 错误码: {error}");
            return;
        }

        // 获取ZIP文件所在的目录和文件名（不含扩展名）
        string zipDirectory = zipPath.GetBaseDir();
        string zipFileName = zipPath.GetFile().GetBaseName(); // 例如 "data"
        string extractBasePath = Path.Combine(zipDirectory, zipFileName);

        // 创建基础的解压目录
        DirAccess dir = DirAccess.Open(zipDirectory);
        if (dir == null)
        {
            GD.PrintErr($"无法访问目录: {zipDirectory}");
            zipReader.Close();
            return;
        }
        
        Error makeDirError = dir.MakeDir(zipFileName);
        if (makeDirError != Error.Ok && makeDirError != Error.AlreadyExists)
        {
            GD.PrintErr($"无法创建目录: {extractBasePath}, 错误码: {makeDirError}");
            zipReader.Close();
            return;
        }

        // 遍历ZIP内的所有文件
        string[] files = zipReader.GetFiles();
        foreach (string filePath in files)
        {
            // 计算文件的完整输出路径
            string fullOutputPath = Path.Combine(extractBasePath, filePath);
            string outputDirectory = fullOutputPath.GetBaseDir();

            // 确保文件的子目录存在
            DirAccess.MakeDirRecursiveAbsolute(outputDirectory);

            // 读取ZIP中的文件数据并写入磁盘
            byte[] fileData = zipReader.ReadFile(filePath);
            if (fileData != null)
            {
                using var file = Godot.FileAccess.Open(fullOutputPath, Godot.FileAccess.ModeFlags.Write);
                if (file != null)
                {
                    file.StoreBuffer(fileData);
                    GD.Print($"已解压: {filePath}");
                }
                else
                {
                    GD.PrintErr($"无法创建输出文件: {fullOutputPath}");
                }
            }
            else
            {
                GD.PrintErr($"无法从ZIP读取文件: {filePath}");
            }
        }

        zipReader.Close();
        GD.Print("解压完成！");
    }

    /// <summary>
    /// 将指定路径的ZIP文件解压到指定路径的文件夹中。
    /// </summary>
    /// <param name="zipPath">ZIP文件的完整路径，例如 "user://ZipFile.zip"</param>
    /// <param name="extractBasePath">解压基础路径，例如 "user://ChartImport/"</param>
    public static void UnzipFileTo(string zipPath, string extractBasePath)
    {
        var zipReader = new ZipReader();
        Error error = zipReader.Open(zipPath);

        if (error != Error.Ok)
        {
            GD.PrintErr($"无法打开ZIP文件: {zipPath}, 错误码: {error}");
            return;
        }

        // 遍历ZIP内的所有文件
        string[] files = zipReader.GetFiles();
        foreach (string filePath in files)// 例如 Chart.json
        {
            // 计算文件的完整输出路径
            string fullOutputPath = Path.Combine(extractBasePath, filePath); // 例如 user://ChartImport/Chart.json
            string outputDirectory = extractBasePath; // 例如 user://ChartImport/

            // 确保文件的子目录存在
            DirAccess.MakeDirRecursiveAbsolute(outputDirectory);

            // 读取ZIP中的文件数据并写入磁盘
            byte[] fileData = zipReader.ReadFile(filePath);
            if (fileData != null)
            {
                using var file = Godot.FileAccess.Open(fullOutputPath, Godot.FileAccess.ModeFlags.Write);
                if (file != null)
                {
                    file.StoreBuffer(fileData);
                    GD.Print($"已解压: {filePath}");
                }
                else
                {
                    GD.PrintErr($"无法创建输出文件: {fullOutputPath}");
                }
            }
            else
            {
                GD.PrintErr($"无法从ZIP读取文件: {filePath}");
            }
        }

        zipReader.Close();
        GD.Print("解压完成！");
    }

    /// <summary>
	/// 根据属性字典生成谱面信息文件
	/// </summary>
	/// <param name="filePath">info.txt的路径</param>
	/// <param name="properties">属性字典</param>
	public static void WriteInfoFile(string filePath, Dictionary<string, string> properties)
	{
		// 参数校验
		if (properties == null)
		{
			GD.PrintErr("属性字典为 null, 无法写入文件。");
			return;
		}

		// 确保文件所在的目录存在
		string directory = filePath.GetBaseDir();
		if (!string.IsNullOrEmpty(directory) && !DirAccess.DirExistsAbsolute(directory))
		{
			DirAccess.MakeDirRecursiveAbsolute(directory);
		}

		// 打开文件（写入模式），如果文件已存在则覆盖
		using var file = Godot.FileAccess.Open(filePath, Godot.FileAccess.ModeFlags.Write);
		if (file == null)
		{
			GD.PrintErr($"无法打开文件进行写入: {filePath}");
			return;
		}

		// 写入可选的注释头（读取时会自动跳过）
		file.StoreLine("# Generated by WriteInfoFile");

		// 写入所有键值对
		foreach (var kvp in properties)
		{
			string line = $"{kvp.Key}: {kvp.Value}";
			file.StoreLine(line);
		}

		// 文件会在 using 块结束时自动关闭
		GD.Print($"成功写入 {properties.Count} 条属性到文件: {filePath}");
	}

    /// <summary>
	/// 读取info.txt谱面信息文件
	/// </summary>
	/// <param name="filePath">info.txt的路径</param>
	/// <returns>一个属性字典</returns>
	public static Dictionary<string, string> ReadInfoFile(string filePath)
	{
		var properties = new Dictionary<string, string>();

		// 检查文件是否存在
		if (!Godot.FileAccess.FileExists(filePath))
		{
			GD.PrintErr($"文件不存在: {filePath}");
			return properties;
		}

		// 以只读文本模式打开文件
		using var file = Godot.FileAccess.Open(filePath, Godot.FileAccess.ModeFlags.Read);
		
		// 逐行读取
		while (file.GetPosition() < file.GetLength())
		{
			string line = file.GetLine().Trim(); // 去除首尾空白

			// 跳过空行和注释行（以#开头）
			if (string.IsNullOrEmpty(line) || line.StartsWith("#"))
				continue;

			// 查找第一个冒号的位置
			int colonIndex = line.IndexOf(':');
			if (colonIndex == -1)
				continue; // 没有冒号的行跳过

			// 提取键和值，并去除各自两端的空白
			string key = line.Substring(0, colonIndex).Trim();
			string value = line.Substring(colonIndex + 1).Trim();

			// 存入字典（如果键重复，后面的会覆盖前面的，根据需求可调整）
			properties[key] = value;
		}

		return properties;
	}

    /// <summary>
	/// 将文件复制到指定路径
	/// </summary>
	/// <param name="sourcePath">源文件的完整路径（支持 res://、user:// 或绝对路径）</param>
	/// <param name="destinationPath">目标文件的完整路径（包含文件名）</param>
	/// <returns>复制成功返回 true，否则返回 false</returns>
	public static bool CopyFile(string sourcePath, string destinationPath)
	{
		// 检查源文件是否存在
		if (!Godot.FileAccess.FileExists(sourcePath))
		{
			GD.PrintErr($"[FileUtil] 源文件不存在: {sourcePath}");
			return false;
		}

		// 确保目标目录存在
		string destDir = destinationPath.GetBaseDir();
		if (!string.IsNullOrEmpty(destDir) && !DirAccess.DirExistsAbsolute(destDir))
		{
			DirAccess.MakeDirRecursiveAbsolute(destDir);
		}

		try
		{
			// 以读取模式打开源文件
			using var sourceFile = Godot.FileAccess.Open(sourcePath, Godot.FileAccess.ModeFlags.Read);
			if (sourceFile == null)
			{
				GD.PrintErr($"[FileUtil] 无法打开源文件: {sourcePath}");
				return false;
			}

			// 以写入模式打开目标文件（如果目标文件已存在，会被覆盖）
			using var destFile = Godot.FileAccess.Open(destinationPath, Godot.FileAccess.ModeFlags.Write);
			if (destFile == null)
			{
				GD.PrintErr($"[FileUtil] 无法创建或打开目标文件: {destinationPath}");
				return false;
			}

			// 逐块复制文件内容（避免大文件占用过多内存）
			const int bufferSize = 8192; // 8 KB 缓冲区
			byte[] buffer = new byte[bufferSize];
			long bytesRemaining = (long)sourceFile.GetLength();
			while (bytesRemaining > 0)
			{
				long bytesToRead = (long)Math.Min(bufferSize, bytesRemaining);
				buffer = sourceFile.GetBuffer(bytesToRead);
				//if (bytesRead <= 0) break; // 读取错误或 EOF

				destFile.StoreBuffer(buffer);
				bytesRemaining -= bytesToRead;
			}

			GD.Print($"[FileUtil] 文件复制成功: {sourcePath} -> {destinationPath}");
			return true;
		}
		catch (Exception e)
		{
			GD.PrintErr($"[FileUtil] 复制文件时发生异常: {e.Message}");
			return false;
		}
	}

	/// <summary>
	/// 确保目录存在，若存在则不执行任何操作，若不存在则创建目录
	/// </summary>
	/// <param name="path">目录路径</param>
	public static void EnsureDirectoryExists(string directory)
	{
        if(string.IsNullOrEmpty(directory)) return;

        string globalPath = ProjectSettings.GlobalizePath(directory);
		if (!DirAccess.DirExistsAbsolute(directory))
		{
			DirAccess.MakeDirRecursiveAbsolute(globalPath);
		}
	}

    public static bool DirExists(string dir)
    {
        string absoluteDir = ProjectSettings.GlobalizePath(dir);

        return DirAccess.DirExistsAbsolute(absoluteDir);
    }

	/// <summary>
	/// 递归删除目录
	/// </summary>
	/// <param name="path">要删除的目录</param>
	public static void DeleteDirectoryRecursive(string path)
    {
        // 打开目录
        using var dir = DirAccess.Open(path);
        if (dir == null)
        {
            GD.PrintErr($"无法打开目录: {path}");
            return;
        }

        // 遍历目录内容
        dir.ListDirBegin();  // 开始列出目录
        string fileName = dir.GetNext();
        while (!string.IsNullOrEmpty(fileName))
        {
            if (fileName == "." || fileName == "..")  // 跳过特殊目录
            {
                fileName = dir.GetNext();
                continue;
            }

            string fullPath = path + "/" + fileName;
            if (dir.CurrentIsDir())
            {
                // 递归删除子目录
                DeleteDirectoryRecursive(fullPath);
            }
            else
            {
                // 删除文件
                DirAccess.RemoveAbsolute(fullPath);  // 静态方法删除文件
            }
            fileName = dir.GetNext();
        }
        dir.ListDirEnd();  // 结束列出目录

        // 删除当前空目录
        DirAccess.RemoveAbsolute(path);
    }

    /// <summary>
    /// 将多个文件打包进一个 ZIP 压缩包。
    /// </summary>
    /// <param name="filePaths">需要打包的文件路径列表（支持 user:// 或绝对路径）</param>
    /// <param name="zipPath">生成的 ZIP 文件的路径</param>
    /// <returns>如果成功返回 true，否则返回 false。</returns>
    public static bool CreateZip(List<string> filePaths, string zipPath)
    {
        // 使用 using 确保 ZipPacker 正确释放资源
        using var packer = new ZipPacker();

        // 1. 打开或创建 ZIP 文件
        // APPEND_CREATE 表示创建一个新的压缩包
        var err = packer.Open(zipPath, ZipPacker.ZipAppend.Create);
        if (err != Error.Ok)
        {
            GD.PrintErr($"无法创建 ZIP 文件 '{zipPath}'，错误代码: {err}");
            return false;
        }

        // 2. 逐个将文件添加到压缩包
        foreach (var filePath in filePaths)
        {
            // 检查源文件是否存在
            if (!Godot.FileAccess.FileExists(filePath))
            {
                GD.PrintErr($"错误：文件未找到，已跳过 '{filePath}'");
                continue;
            }

            // 2.1. 读取整个文件内容
            byte[] fileData;
            try
            {
                fileData = Godot.FileAccess.GetFileAsBytes(filePath);
            }
            catch (Exception e)
            {
                GD.PrintErr($"读取文件 '{filePath}' 时出错: {e.Message}");
                continue;
            }

            // 2.2. 生成在压缩包内的存储路径
            // 使用文件名作为存储路径，如需保留目录结构可修改此逻辑
            var targetPath = Path.GetFileName(filePath);

            // 2.3. 开始写入文件
            // 可在此处指定压缩级别，ZipPacker.CompressionLevel
            err = packer.StartFile(targetPath);
            if (err != Error.Ok)
            {
                GD.PrintErr($"无法在压缩包中开始写入文件 '{targetPath}'，错误代码: {err}");
                continue;
            }

            // 2.4. 写入文件数据
            err = packer.WriteFile(fileData);
            if (err != Error.Ok)
            {
                GD.PrintErr($"写入文件数据 '{targetPath}' 时出错，错误代码: {err}");
            }

            // 2.5. 关闭当前文件（必须配对调用）
            err = packer.CloseFile();
            if (err != Error.Ok)
            {
                GD.PrintErr($"关闭文件 '{targetPath}' 时出错，错误代码: {err}");
            }
        }

        // 3. 关闭并最终化 ZIP 文件
        err = packer.Close();
        if (err != Error.Ok)
        {
            GD.PrintErr($"最终化 ZIP 文件 '{zipPath}' 时出错，错误代码: {err}");
        	return false;
        }
		
		GD.Print($"成功创建 ZIP 文件: '{zipPath}'");
        return true;

        
    }

    /// <summary>
    /// 获取目录下按字典序排列的文件（不含子目录）
    /// 返回相对路径或完整路径
    /// </summary>
    public static string[] GetFilesInDir(string dirPath, bool fullPath = true)
    {
        using var dir = DirAccess.Open(dirPath);
        if (dir == null)
        {
            GD.PrintErr($"无法打开目录: {dirPath}, 错误码: {DirAccess.GetOpenError()}");
            return null;
        }

        // 只获取文件（不含子目录）
        string[] files = dir.GetFiles();
        if (files.Length == 0)
            return null;

        // PackedStringArray 自带 Sort()，按字典序原地排序
        Array.Sort(files);

        // 如果需要完整路径，用 Godot 的 PathJoin 拼接
        if (fullPath)
        {
            for(int i = 0; i < files.Length; i++)
            {
                files[i] = dirPath.PathJoin(files[i]);
            }
        }
        
        return files;
    }

    /// <summary>
    /// 获取目录下按字典序排列的第一个文件（不含子目录）
    /// 返回相对路径或完整路径
    /// </summary>
    public static string GetFirstFileAlphabetically(string dirPath, bool fullPath = true)
    {
        using var dir = DirAccess.Open(dirPath);
        if (dir == null)
        {
            GD.PrintErr($"[{Name}] 无法打开目录: {dirPath}, 错误码: {DirAccess.GetOpenError()}");
            return null;
        }

        // 只获取文件（不含子目录）
        var files = dir.GetFiles();
        if (files.Length == 0)
            return null;

        // PackedStringArray 自带 Sort()，按字典序原地排序
        Array.Sort(files);

        string firstFile = files[0];

        // 如果需要完整路径，用 Godot 的 PathJoin 拼接
        return fullPath ? dirPath.PathJoin(firstFile) : firstFile;
    }

    public static string[] GetDirsInDir(string dirPath, bool fullPath = true)
    {
        using var dir = DirAccess.Open(dirPath);
        if (dir == null)
        {
            GD.PrintErr($"[{Name}] 无法打开目录: {dirPath}, 错误码: {DirAccess.GetOpenError()}");
            return null;
        }

        // 只获取目录（不含子目录）
        string[] dirs = dir.GetDirectories();
        if (dirs.Length == 0)
            return null;

        // PackedStringArray 自带 Sort()，按字典序原地排序
        Array.Sort(dirs);

        // 如果需要完整路径，用 Godot 的 PathJoin 拼接
        if (fullPath)
        {
            for(int i = 0; i < dirs.Length; i++)
            {
                dirs[i] = dirPath.PathJoin(dirs[i]);
            }
        }
        
        return dirs;
    }

    /// <summary>
    /// 根据文件扩展名，动态加载不同格式的音频文件。
    /// </summary>
    /// <param name="path">音频文件的路径</param>
    /// <returns>加载成功的 AudioStream 对象，失败时返回 null</returns>
    public static AudioStream LoadAudioFromFile(string path)
    {
        if (!Godot.FileAccess.FileExists(path))
        {
            GD.PrintErr($"[Util] 音频文件不存在: {path}");
            return null;
        }

        string extension = Path.GetExtension(path).ToLowerInvariant();

        switch (extension)
        {
            case ".mp3":
                using (var file = Godot.FileAccess.Open(path, Godot.FileAccess.ModeFlags.Read))
                {
                    byte[] data = file.GetBuffer((long)file.GetLength());
                    var mp3Stream = new AudioStreamMP3 { Data = data };
                    return mp3Stream;
                }

            case ".ogg":
                var oggStream = AudioStreamOggVorbis.LoadFromFile(path);
                if (oggStream == null)
                    GD.PrintErr($"[Util] 加载 OGG 文件失败: {path}");
                return oggStream;

            case ".wav":
                var wavStream = AudioStreamWav.LoadFromFile(path);
                if (wavStream == null)
                    GD.PrintErr($"[Util] 加载 WAV 文件失败: {path}");
                return wavStream;

            default:
                GD.PrintErr($"[Util] 不支持的音频格式: {extension}");
                return null;
        }
    }

    /// <summary>
    /// 通过文件头(Magic Number)检测图片真实格式
    /// 支持: jpg, png, webp, bmp, ktx, svg
    /// </summary>
    public static string DetectImageFormat(byte[] buffer)
    {
        if (buffer == null || buffer.Length < 4)
            return "unknown";

        // JPEG: FF D8 FF
        if (buffer[0] == 0xFF && buffer[1] == 0xD8 && buffer[2] == 0xFF)
            return "jpg";

        // PNG: 89 50 4E 47
        if (buffer[0] == 0x89 && buffer[1] == 0x50 && buffer[2] == 0x4E && buffer[3] == 0x47)
            return "png";

        // WebP: RIFF....WEBP
        if (buffer.Length >= 12 && buffer[0] == 0x52 && buffer[1] == 0x49 && buffer[2] == 0x46 && buffer[3] == 0x46)
        {
            if (buffer[8] == 0x57 && buffer[9] == 0x45 && buffer[10] == 0x42 && buffer[11] == 0x50)
                return "webp";
        }

        // BMP: BM
        if (buffer[0] == 0x42 && buffer[1] == 0x4D)
            return "bmp";

        // KTX (KTX1/KTX2): AB 4B 54 58 20 3x 3x BB 0D 0A 1A 0A
        if (buffer.Length >= 12 &&
            buffer[0] == 0xAB && buffer[1] == 0x4B &&
            buffer[2] == 0x54 && buffer[3] == 0x58)
        {
            return "ktx";
        }

        // SVG: 文本格式，以 <?xml 或 <svg 开头（可能带 UTF-8 BOM）
        if (buffer[0] == 0x3C || buffer[0] == 0xEF) // '<' 或 BOM
        {
            int checkLen = Math.Min(buffer.Length, 256);
            try
            {
                string text = Encoding.UTF8.GetString(buffer, 0, checkLen).TrimStart();
                if (text.StartsWith("<?xml", StringComparison.OrdinalIgnoreCase) ||
                    text.StartsWith("<svg", StringComparison.OrdinalIgnoreCase))
                {
                    return "svg";
                }
            }
            catch { /* 忽略编码错误 */ }
        }

        // TGA 没有可靠 Magic Number，不在这里检测，放 fallback 兜底
        return "unknown";
    }

    /// <summary>
    /// 智能加载路径中的图片为Texture2D
    /// 可以识别出扩展名与实际格式不匹配的问题
    /// </summary>
    /// <param name="picPath">图片路径</param>
    /// <returns></returns>
    public static Texture2D LoadTextureFromFile(string picPath, out string realFormat, bool mipmap = true)
    {
        realFormat = null;
        // 检查文件存在
        if (!Godot.FileAccess.FileExists(picPath))
        {
            GD.PrintErr($"[{Name}] UpdateItemDisplay() 文件不存在:{picPath}");
            return null;
        }

        var image = new Image();
        Error err = Error.Failed;

        // 1. 通用加载（扩展名和格式一致时直接成功）
        err = image.Load(picPath);

        // 2. 失败则回退到 Buffer + 格式检测
        if (err != Error.Ok)
        {
            GD.Print($"[{Name}] LoadFromFile 失败，回退到 Buffer 解码: {picPath}");
            
            // 重新创建实例，避免之前失败的状态残留
            image = new Image();

            using Godot.FileAccess file = Godot.FileAccess.Open(picPath, Godot.FileAccess.ModeFlags.Read);
            ulong fileSize = file.GetLength();
            byte[] buffer = file.GetBuffer((long)fileSize);

            string format = DetectImageFormat(buffer);
            GD.Print($"[{Name}] 检测到真实格式: {format}, 大小: {fileSize} bytes");
            realFormat = format;

            switch (format)
            {
                case "jpg":
                    err = image.LoadJpgFromBuffer(buffer);
                    break;
                case "png":
                    err = image.LoadPngFromBuffer(buffer);
                    break;
                case "webp":
                    err = image.LoadWebpFromBuffer(buffer);
                    break;
                case "bmp":
                    err = image.LoadBmpFromBuffer(buffer);
                    break;
                case "ktx":
                    err = image.LoadKtxFromBuffer(buffer);
                    break;
                case "svg":
                    err = image.LoadSvgFromBuffer(buffer);
                    break;
                default:
                    // 兜底逐个尝试（含无 Magic Number 的 TGA）
                    err = image.LoadJpgFromBuffer(buffer);
                    if (err != Error.Ok) err = image.LoadPngFromBuffer(buffer);
                    if (err != Error.Ok) err = image.LoadWebpFromBuffer(buffer);
                    if (err != Error.Ok) err = image.LoadBmpFromBuffer(buffer);
                    if (err != Error.Ok) err = image.LoadKtxFromBuffer(buffer);
                    if (err != Error.Ok) err = image.LoadSvgFromBuffer(buffer);
                    if (err != Error.Ok) err = image.LoadTgaFromBuffer(buffer);
                    break;
            }
        }

        if (err != Error.Ok)
        {
            GD.PrintErr($"[{Name}] 所有格式解码均失败:{picPath}");
            return null;
        }

        // 检查尺寸
        if (image.GetWidth() > 16384 || image.GetHeight() > 16384)
        {
            GD.PrintErr($"[{Name}] 图片尺寸{image.GetWidth()}x{image.GetHeight()}超过 Godot 限制 (16384x16384)");
            return null;
        }

        // 生成mipmap
        if (mipmap)
        {
            err = image.GenerateMipmaps();
            if (err != Error.Ok)
            {
                GD.PushWarning($"[{Name}] 生成 Mipmap 失败 ({picPath}): {err}，将使用无 Mipmap 的纹理");
            }
        }


        Texture2D texture = ImageTexture.CreateFromImage(image);
        if(texture == null)
        {
            GD.PrintErr($"[{Name}] UpdateItemDisplay() texture == null picturePath:{picPath}");
            return null;
        }

        return texture;
    }

}
