using Godot;
using System;
using QuickType;
using System.Text.Json;
using Newtonsoft.Json;

public partial class ChartLoader : Node
{
    
    public bool isExtractZip = false;

    public override void _Ready()
    {
        base._Ready();
        

        // // 使用带路径的加载方法
        // string loadPath = "res://Chart.json";
        // chart = LoadChart(loadPath);

        // if (chart == null)
        // {
        //     GD.PrintErr("铺面导入失败");
        // }
        // else
        // {
        //     GD.Print("铺面导入成功");
        //     GD.Print(chart.ChartTime);
        // }

        // // 保存到另一个路径
        // string savePath = "res://Chart2.json";
        // SaveChart(chart, savePath);

        //zipExtractor.UnzipFileTo("res://Snow Desert.zip", "res://ChartImport");

    }

    /// <summary>
    /// 从指定路径加载 Chart 数据
    /// </summary>
    /// <param name="path">Godot 资源路径（如 res://Chart.json）或绝对路径</param>
    /// <returns>反序列化后的 Chart 对象，失败返回 null</returns>
    public static Chart LoadChart(string path)
    {
        // 1. 参数校验
        if (string.IsNullOrEmpty(path))
        {
            GD.PrintErr("文件路径不能为空");
            return null;
        }

        // 2. 检查文件是否存在
        if (!FileAccess.FileExists(path))
        {
            GD.PrintErr($"文件不存在: {path}");
            return null;
        }

        // 3. 打开文件
        var file = FileAccess.Open(path, FileAccess.ModeFlags.Read);
        if (file == null)
        {
            GD.PrintErr($"无法打开文件: {path}");
            return null;
        }

        // 4. 读取 JSON 字符串
        string jsonData = file.GetAsText();
        file.Dispose();

        // 5. 使用生成的 FromJson 方法反序列化（包含正确的转换器设置）
        try
        {
            Chart data = Chart.FromJson(jsonData);
            return data;
        }
        catch (Exception ex)
        {
            GD.PrintErr($"反序列化失败: {ex.Message}\n路径: {path}");
            return null;
        }
    }

    /// <summary>
    /// 将 Chart 数据保存到指定路径
    /// </summary>
    /// <param name="data">要保存的 Chart 对象</param>
    /// <param name="path">保存路径（如 user://Chart2.json）</param>
    public static void SaveChart(Chart data, string path)
    {
        if (data == null)
        {
            GD.PrintErr("保存失败：Chart 数据为 null");
            return;
        }

        if (string.IsNullOrEmpty(path))
        {
            GD.PrintErr("保存路径不能为空");
            return;
        }

        // 使用生成的 ToJson 方法序列化（保持一致性）
        string jsonData = data.ToJson();

        var file = FileAccess.Open(path, FileAccess.ModeFlags.Write);
        if (file == null)
        {
            GD.PrintErr($"无法创建/写入文件: {path}");
            return;
        }

        file.StoreString(jsonData);
        file.Dispose();
        GD.Print($"Chart 已保存到: {path}");
    }
    
}





// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var response = Response.FromJson(jsonString);

namespace QuickType
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Chart
    {
        [JsonProperty("BPMList")]
        public BpmEvent[] BpmList { get; set; }

        [JsonProperty("META")]
        public Meta Meta { get; set; }

        [JsonProperty("chartTime")]
        public float ChartTime { get; set; }

        [JsonProperty("judgeLineGroup")]
        public string[] JudgeLineGroup { get; set; }

        [JsonProperty("judgeLineList")]
        public JudgeLine[] JudgeLineList { get; set; }

        // [JsonProperty("multiLineString")]
        // public string MultiLineString { get; set; }

        // [JsonProperty("multiScale")]
        // public int MultiScale { get; set; }
    }

    public partial class BpmEvent
    {
        [JsonProperty("bpm")]
        public float Bpm { get; set; }

        [JsonProperty("startTime")]
        public int[] StartTime { get; set; }
    }

    public partial class JudgeLine
    {
        [JsonProperty("Group")]
        public int Group { get; set; }

        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("Texture")]
        public string Texture { get; set; }

        [JsonProperty("alphaControl")]
        public AlphaControl[] AlphaControl { get; set; }

        [JsonProperty("anchor")]
        public float[] Anchor { get; set; }

        [JsonProperty("bpmfactor")]
        public float Bpmfactor { get; set; }

        [JsonProperty("eventLayers")]
        public EventLayer[] EventLayers { get; set; }

        [JsonProperty("extended")]
        public Extended Extended { get; set; }

        [JsonProperty("father")]
        public int Father { get; set; }

        [JsonProperty("isCover")]
        public int IsCover { get; set; }

        [JsonProperty("isGif")]
        public bool IsGif { get; set; }

        [JsonProperty("notes", NullValueHandling = NullValueHandling.Ignore)]
        public Note[] Notes { get; set; }

        [JsonProperty("numOfNotes")]
        public int NumOfNotes { get; set; }

        [JsonProperty("posControl")]
        public PosControl[] PosControl { get; set; }

        [JsonProperty("sizeControl")]
        public SizeControl[] SizeControl { get; set; }

        [JsonProperty("skewControl")]
        public SkewControl[] SkewControl { get; set; }

        [JsonProperty("yControl")]
        public YControl[] YControl { get; set; }

        [JsonProperty("zOrder")]
        public int ZOrder { get; set; }
    }

    public partial class AlphaControl
    {
        [JsonProperty("alpha")]
        public float Alpha { get; set; }

        [JsonProperty("easing")]
        public int Easing { get; set; }

        [JsonProperty("x")]
        public float X { get; set; }
    }

    public partial class EventLayer
    {
        [JsonProperty("alphaEvents")]
        public LineEvent[] AlphaEvents { get; set; }

        [JsonProperty("moveXEvents")]
        public LineEvent[] MoveXEvents { get; set; }

        [JsonProperty("moveYEvents")]
        public LineEvent[] MoveYEvents { get; set; }

        [JsonProperty("rotateEvents")]
        public LineEvent[] RotateEvents { get; set; }

        [JsonProperty("speedEvents", NullValueHandling = NullValueHandling.Ignore)]
        public LineEvent[] SpeedEvents { get; set; }
    }

    public partial class LineEvent
    {
        [JsonProperty("bezier")]
        public int Bezier { get; set; }

        [JsonProperty("bezierPoints")]
        public float[] BezierPoints { get; set; }

        [JsonProperty("easingLeft")]
        public float EasingLeft { get; set; }

        [JsonProperty("easingRight")]
        public float EasingRight { get; set; }

        [JsonProperty("easingType")]
        public int EasingType { get; set; }

        [JsonProperty("end")]
        public float End { get; set; }

        [JsonProperty("endTime")]
        public int[] EndTime { get; set; }

        [JsonProperty("linkgroup")]
        public int Linkgroup { get; set; }

        [JsonProperty("start")]
        public float Start { get; set; }

        [JsonProperty("startTime")]
        public int[] StartTime { get; set; }
    }

    // public partial class SpeedEvent
    // {
    //     [JsonProperty("end")]
    //     public float End { get; set; }

    //     [JsonProperty("endTime")]
    //     public int[] EndTime { get; set; }

    //     [JsonProperty("linkgroup")]
    //     public int Linkgroup { get; set; }

    //     [JsonProperty("start")]
    //     public float Start { get; set; }

    //     [JsonProperty("startTime")]
    //     public int[] StartTime { get; set; }
    // }

    public partial class Extended
    {
        [JsonProperty("inclineEvents")]
        public LineEvent[] InclineEvents { get; set; }

        [JsonProperty("scaleXEvents", NullValueHandling = NullValueHandling.Ignore)]
        public LineEvent[] ScaleXEvents { get; set; }
    }

    public partial class Note
    {
        [JsonProperty("above")]
        public int Above { get; set; }

        [JsonProperty("alpha")]
        public float Alpha { get; set; }

        [JsonProperty("endTime")]
        public int[] EndTime { get; set; }

        [JsonProperty("isFake")]
        public bool IsFake { get; set; }

        [JsonProperty("positionX")]
        public float PositionX { get; set; }

        [JsonProperty("size")]
        public float Size { get; set; }

        [JsonProperty("speed")]
        public float Speed { get; set; }

        [JsonProperty("startTime")]
        public int[] StartTime { get; set; }

        [JsonProperty("type")]
        public int Type { get; set; }

        [JsonProperty("visibleTime")]
        public float VisibleTime { get; set; }

        [JsonProperty("yOffset")]
        public float YOffset { get; set; }
    }

    public partial class PosControl
    {
        [JsonProperty("easing")]
        public int Easing { get; set; }

        [JsonProperty("pos")]
        public float Pos { get; set; }

        [JsonProperty("x")]
        public float X { get; set; }
    }

    public partial class SizeControl
    {
        [JsonProperty("easing")]
        public int Easing { get; set; }

        [JsonProperty("size")]
        public float Size { get; set; }

        [JsonProperty("x")]
        public float X { get; set; }
    }

    public partial class SkewControl
    {
        [JsonProperty("easing")]
        public int Easing { get; set; }

        [JsonProperty("skew")]
        public float Skew { get; set; }

        [JsonProperty("x")]
        public float X { get; set; }
    }

    public partial class YControl
    {
        [JsonProperty("easing")]
        public int Easing { get; set; }

        [JsonProperty("x")]
        public float X { get; set; }

        [JsonProperty("y")]
        public float Y { get; set; }
    }

    public partial class Meta
    {
        [JsonProperty("RPEVersion")]
        public int RpeVersion { get; set; }

        [JsonProperty("background")]
        public string Background { get; set; }

        [JsonProperty("charter")]
        public string Charter { get; set; }

        [JsonProperty("composer")]
        public string Composer { get; set; }

        [JsonProperty("duration")]
        public float Duration { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("illustration")]
        public string Illustration { get; set; }

        [JsonProperty("level")]
        public string Level { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("offset")]
        public float Offset { get; set; }

        [JsonProperty("song")]
        public string Song { get; set; }
    }

    //public enum Name { Untitled };

    //public enum Texture { LinePng };

    public partial class Chart
    {
        public static Chart FromJson(string json) => JsonConvert.DeserializeObject<Chart>(json, QuickType.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Chart self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                /*NameConverter.Singleton,*/
                /*TextureConverter.Singleton,*/
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    // internal class NameConverter : JsonConverter
    // {
    //     public override bool CanConvert(Type t) => t == typeof(Name) || t == typeof(Name?);

    //     public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
    //     {
    //         if (reader.TokenType == JsonToken.Null) return null;
    //         var value = serializer.Deserialize<string>(reader);
    //         if (value == "Untitled")
    //         {
    //             return Name.Untitled;
    //         }
    //         throw new Exception("Cannot unmarshal type Name");
    //     }

    //     public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
    //     {
    //         if (untypedValue == null)
    //         {
    //             serializer.Serialize(writer, null);
    //             return;
    //         }
    //         var value = (Name)untypedValue;
    //         if (value == Name.Untitled)
    //         {
    //             serializer.Serialize(writer, "Untitled");
    //             return;
    //         }
    //         throw new Exception("Cannot marshal type Name");
    //     }

    //     public static readonly NameConverter Singleton = new NameConverter();
    // }

    // internal class TextureConverter : JsonConverter
    // {
    //     public override bool CanConvert(Type t) => t == typeof(Texture) || t == typeof(Texture?);

    //     public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
    //     {
    //         if (reader.TokenType == JsonToken.Null) return null;
    //         var value = serializer.Deserialize<string>(reader);
    //         if (value == "line.png")
    //         {
    //             return Texture.LinePng;
    //         }
    //         throw new Exception("Cannot unmarshal type Texture");
    //     }

    //     public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
    //     {
    //         if (untypedValue == null)
    //         {
    //             serializer.Serialize(writer, null);
    //             return;
    //         }
    //         var value = (Texture)untypedValue;
    //         if (value == Texture.LinePng)
    //         {
    //             serializer.Serialize(writer, "line.png");
    //             return;
    //         }
    //         throw new Exception("Cannot marshal type Texture");
    //     }

    //     public static readonly TextureConverter Singleton = new TextureConverter();
    // }

    public partial class LineEvent
    {
        [JsonIgnore] public float startSec;
        [JsonIgnore] public float endSec;

        // 仅在速度事件中有效，在此事件的StartTime之前的所有位移，前缀和优化
        [JsonIgnore] public float prefixX; 
    }

    public partial class Note
    {
        [JsonIgnore] public float startSec;
        [JsonIgnore] public float endSec;

        /// <summary>
        /// note所在时刻累积的所有位移，用于优化性能
        /// </summary>
        [JsonIgnore] public float allDisplacement;
    }
}
