// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var response = Response.FromJson(jsonString);

namespace QuickType
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.Threading;

    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public class Beat : IComparable<Beat>
    {
        private int[] _values = new int[3];

        public int[] Values { get => _values; }

        public int IntegerPart => _values[0];
        public int Numerator   => _values[1];
        public int Denominator  => _values[2];

        public override string ToString()
        {
            return $"[{_values[0]},{_values[1]},{_values[2]}]";
        }

        public int this[int index]
        {
            get
            {
                return _values[index];
            }
            set
            {
                _values[index] = value;
            }
        }

        public Beat Duplicate()
        {
            return new Beat
            {
                _values = [_values[0], _values[1], _values[2]]
            };
        }

        public Beat(){}
        
        public Beat(int[] values)
        {
            if (values.Length != 3)
                throw new ArgumentException("Beat元素个数必须为3", nameof(values));
            if (values[2] == 0)
                throw new ArgumentException("分母不能为0", nameof(values));
        
            // 复制数组，避免外部修改影响内部状态
            Array.Copy(values, this._values, 3);
            
        }

        public Beat(int a, int b, int c)
        {
            if (c == 0)
                throw new ArgumentException("分母不能为0", nameof(c));
            this._values[0] = a;
            this._values[1] = b;
            this._values[2] = c;
        }

        public int CompareTo(Beat other)
        {
            if (other is null) return 1; // this > null

            // 先比较整数部分
            int cmp = IntegerPart.CompareTo(other.IntegerPart);
            if (cmp != 0) return cmp;

            // 分数部分比较：a/b < c/d  <=>  ad < bc（分母为正）
            long left = (long)Numerator * other.Denominator;
            long right = (long)Denominator * other.Numerator;
            return left.CompareTo(right);
        }

        // -------- 重载比较运算符（>, <, >=, <=）--------
        // 这些运算符必须成对重载
        public static bool operator >(Beat left, Beat right)
        {
            // 先处理 null 值，避免空引用异常
            if (left is null) return false;
            if (right is null) return true;  // left 非空 > null
            
            return left.CompareTo(right) > 0;

        }

        public static bool operator <(Beat left, Beat right)
        {
            if (left is null) return right is not null; // null < 非空
            if (right is null) return false;

            return left.CompareTo(right) < 0;
        }

        public static bool operator >=(Beat left, Beat right)
        {
            if (left is null) return right is null;
            if (right is null) return true;

            return left.CompareTo(right) >= 0;
        }

        public static bool operator <=(Beat left, Beat right)
        {
            if (left is null) return true;
            if (right is null) return false; // left非空

            return left.CompareTo(right) <= 0;
        }

        // -------- 重载相等运算符 (==, !=) --------
        // 注意：重载 == 和 != 是强制的（如果重载了 > 和 <，编译器会警告，建议一起重载）
        public static bool operator ==(Beat left, Beat right)
        {
            // 如果两侧都是 null，返回 true
            if (left is null && right is null) return true;
            if (left is null || right is null) return false;
            
            // 比较值是否相同
            return left._values[0] == right._values[0]
                && left._values[1] == right._values[1]
                && left._values[2] == right._values[2];
        }

        public static bool operator !=(Beat left, Beat right)
        {
            return !(left == right);
        }

        // 重写 Equals 和 GetHashCode（任何时候重载 == 都必须这么做，消除编译器警告）
        public override bool Equals(object obj)
        {
            return this == obj as Beat;
        }

        // -------- 实现 GetHashCode --------
        public override int GetHashCode()
        {
            // 使用 System.HashCode 组合三个字段（.NET Core 2.1+ / .NET 5+）
            // 若目标框架不支持，可手动组合： (a * 397) ^ b ^ (c << 16) 等
            return HashCode.Combine(_values[0], _values[1], _values[2]);
        }

    }

    public partial class Chart
    {
        [JsonProperty("BPMList")]
        public BpmEvent[] BpmList { get; set; }

        [JsonProperty("META")]
        public Meta Meta { get; set; }

        [JsonProperty("chartTime")]
        public float ChartTime { get; set; }

        [JsonProperty("judgeLineGroup")]
        public string[] JudgeLineGroup { get; set; }

        [JsonProperty("judgeLineList")]
        public List<JudgeLine> JudgeLineList { get; set; }

        // [JsonProperty("multiLineString")]
        // public string MultiLineString { get; set; }

        // [JsonProperty("multiScale")]
        // public int MultiScale { get; set; }
    }

    public partial class BpmEvent
    {
        [JsonProperty("bpm")]
        public float Bpm { get; set; }

        [JsonProperty("startTime")]
        public int[] StartTime { get; set; }
    }

    public partial class JudgeLine
    {
        [JsonProperty("Group")]
        public int Group { get; set; }

        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("Texture")]
        public string Texture { get; set; }

        [JsonProperty("alphaControl")]
        public AlphaControl[] AlphaControl { get; set; }

        [JsonProperty("anchor")]
        public float[] Anchor { get; set; }

        [JsonProperty("bpmfactor")]
        public float Bpmfactor { get; set; }

        [JsonProperty("eventLayers")]
        public EventLayer[] EventLayers { get; set; }

        [JsonProperty("extended", NullValueHandling = NullValueHandling.Ignore)]
        public Extended Extended { get; set; }

        [JsonProperty("father")]
        public int Father { get; set; }

        [JsonProperty("isCover")]
        public int IsCover { get; set; }

        [JsonProperty("isGif")]
        public bool IsGif { get; set; }

        [JsonProperty("notes", NullValueHandling = NullValueHandling.Ignore)]
        public List<Note> Notes { get; set; }

        [JsonProperty("numOfNotes")]
        public int NumOfNotes { get; set; }

        [JsonProperty("posControl")]
        public PosControl[] PosControl { get; set; }

        [JsonProperty("sizeControl")]
        public SizeControl[] SizeControl { get; set; }

        [JsonProperty("skewControl")]
        public SkewControl[] SkewControl { get; set; }

        [JsonProperty("yControl")]
        public YControl[] YControl { get; set; }

        [JsonProperty("zOrder")]
        public int ZOrder { get; set; }
    }

    public partial class AlphaControl
    {
        [JsonProperty("alpha")]
        public float Alpha { get; set; }

        [JsonProperty("easing")]
        public int Easing { get; set; }

        [JsonProperty("x")]
        public float X { get; set; }
    }

    public partial class EventLayer
    {
        [JsonProperty("alphaEvents", NullValueHandling = NullValueHandling.Ignore)]
        public List<LineEvent> AlphaEvents { get; set; }

        [JsonProperty("moveXEvents", NullValueHandling = NullValueHandling.Ignore)]
        public List<LineEvent> MoveXEvents { get; set; }

        [JsonProperty("moveYEvents", NullValueHandling = NullValueHandling.Ignore)]
        public List<LineEvent> MoveYEvents { get; set; }

        [JsonProperty("rotateEvents", NullValueHandling = NullValueHandling.Ignore)]
        public List<LineEvent> RotateEvents { get; set; }

        [JsonProperty("speedEvents", NullValueHandling = NullValueHandling.Ignore)]
        public List<LineEvent> SpeedEvents { get; set; }
    }

    public enum LineEventEnum
    {
        MoveX,
        MoveY,
        Rotate,
        Alpha,
        Speed,
        //TODO 特殊事件枚举
    }

    public partial class LineEvent
    {
        [JsonProperty("bezier")]
        public bool Bezier { get; set; }

        [JsonProperty("bezierPoints")]
        public float[] BezierPoints { get; set; }

        [JsonProperty("easingLeft")]
        public float EasingLeft { get; set; }

        [JsonProperty("easingRight")]
        public float EasingRight { get; set; }

        [JsonProperty("easingType")]
        public int EasingType { get; set; }

        [JsonProperty("end")]
        public float End { get; set; }

        [JsonProperty("endTime")]
        public int[] EndTime { get; set; }

        [JsonProperty("linkgroup")]
        public int Linkgroup { get; set; }

        [JsonProperty("start")]
        public float Start { get; set; }

        [JsonProperty("startTime")]
        public int[] StartTime { get; set; }
    }

    /// <summary>
    /// LineEvent的属性类型(枚举)
    /// </summary>
    public enum LineEventPropertyType
    {
        Start, End,
        StartTime, EndTime,
        EasingType, EasingLeft, EasingRight,
        Bezier, BezierPoints,

    }


    // public partial class SpeedEvent
    // {
    //     [JsonProperty("end")]
    //     public float End { get; set; }

    //     [JsonProperty("endTime")]
    //     public int[] EndTime { get; set; }

    //     [JsonProperty("linkgroup")]
    //     public int Linkgroup { get; set; }

    //     [JsonProperty("start")]
    //     public float Start { get; set; }

    //     [JsonProperty("startTime")]
    //     public int[] StartTime { get; set; }
    // }

    public partial class Extended
    {
        [JsonProperty("inclineEvents", NullValueHandling = NullValueHandling.Ignore)]
        public LineEvent[] InclineEvents { get; set; }

        [JsonProperty("colorEvents", NullValueHandling = NullValueHandling.Ignore)]
        public ColorEvent[] ColorEvents { get; set; }

        [JsonProperty("scaleXEvents", NullValueHandling = NullValueHandling.Ignore)]
        public LineEvent[] ScaleXEvents { get; set; }

        [JsonProperty("scaleYEvents", NullValueHandling = NullValueHandling.Ignore)]
        public LineEvent[] ScaleYEvents { get; set; }

        [JsonProperty("textEvents", NullValueHandling = NullValueHandling.Ignore)]
        public TextEvent[] TextEvents { get; set; }
    }

    public partial class ColorEvent
    {
        [JsonProperty("bezier")]
        public bool Bezier { get; set; }

        [JsonProperty("bezierPoints")]
        public float[] BezierPoints { get; set; }

        [JsonProperty("easingLeft")]
        public float EasingLeft { get; set; }

        [JsonProperty("easingRight")]
        public float EasingRight { get; set; }

        [JsonProperty("easingType")]
        public int EasingType { get; set; }

        [JsonProperty("end")]
        public int[] End { get; set; }

        [JsonProperty("endTime")]
        public int[] EndTime { get; set; }

        [JsonProperty("linkgroup")]
        public int Linkgroup { get; set; }

        [JsonProperty("start")]
        public int[] Start { get; set; }

        [JsonProperty("startTime")]
        public int[] StartTime { get; set; }
    }

    public partial class TextEvent
    {
        [JsonProperty("bezier")]
        public long Bezier { get; set; }

        [JsonProperty("bezierPoints")]
        public long[] BezierPoints { get; set; }

        [JsonProperty("easingLeft")]
        public long EasingLeft { get; set; }

        [JsonProperty("easingRight")]
        public long EasingRight { get; set; }

        [JsonProperty("easingType")]
        public long EasingType { get; set; }

        [JsonProperty("end")]
        public string End { get; set; }

        [JsonProperty("endTime")]
        public long[] EndTime { get; set; }

        [JsonProperty("font")]
        public string Font { get; set; }

        [JsonProperty("linkgroup")]
        public long Linkgroup { get; set; }

        [JsonProperty("start")]
        public string Start { get; set; }

        [JsonProperty("startTime")]
        public long[] StartTime { get; set; }
    }

    public partial class Note
    {
        [JsonProperty("above")]
        public int Above { get; set; } // 音符翻转 1表示上面，2表示下面

        [JsonProperty("alpha")]
        public float Alpha { get; set; }

        [JsonProperty("endTime")]
        public int[] EndTime { get; set; }

        [JsonProperty("isFake")]
        public bool IsFake { get; set; }

        [JsonProperty("positionX")]
        public float PositionX { get; set; }

        [JsonProperty("size")]
        public float Size { get; set; }

        [JsonProperty("speed")]
        public float Speed { get; set; }

        [JsonProperty("startTime")]
        public int[] StartTime { get; set; }

        [JsonProperty("type")]
        public int Type { get; set; }

        [JsonProperty("visibleTime")]
        public float VisibleTime { get; set; }

        [JsonProperty("yOffset")]
        public float YOffset { get; set; }
    }

    /// <summary>
    /// note的属性类型(枚举)
    /// </summary>
    public enum NotePropertyEnum
    {
        Above,
        Alpha,
        StartTime, EndTime, 
        IsFake,
        PosX,
        Size,
        Type,
        VisibleTime,
        YOffset
    }

    public partial class PosControl
    {
        [JsonProperty("easing")]
        public int Easing { get; set; }

        [JsonProperty("pos")]
        public float Pos { get; set; }

        [JsonProperty("x")]
        public float X { get; set; }
    }

    public partial class SizeControl
    {
        [JsonProperty("easing")]
        public int Easing { get; set; }

        [JsonProperty("size")]
        public float Size { get; set; }

        [JsonProperty("x")]
        public float X { get; set; }
    }

    public partial class SkewControl
    {
        [JsonProperty("easing")]
        public int Easing { get; set; }

        [JsonProperty("skew")]
        public float Skew { get; set; }

        [JsonProperty("x")]
        public float X { get; set; }
    }

    public partial class YControl
    {
        [JsonProperty("easing")]
        public int Easing { get; set; }

        [JsonProperty("x")]
        public float X { get; set; }

        [JsonProperty("y")]
        public float Y { get; set; }
    }

    public partial class Meta
    {
        [JsonProperty("RPEVersion")]
        public int RpeVersion { get; set; }

        [JsonProperty("background")]
        public string Background { get; set; }

        [JsonProperty("charter")]
        public string Charter { get; set; }

        [JsonProperty("composer")]
        public string Composer { get; set; }

        [JsonProperty("duration")]
        public float Duration { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("illustration")]
        public string Illustration { get; set; }

        [JsonProperty("level")]
        public string Level { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("offset")]
        public float Offset { get; set; }

        [JsonProperty("song")]
        public string Song { get; set; }
    }

    //public enum Name { Untitled };

    //public enum Texture { LinePng };

    public partial class Chart
    {
        public static Chart FromJson(string json) => JsonConvert.DeserializeObject<Chart>(json, QuickType.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Chart self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                /*NameConverter.Singleton,*/
                /*TextureConverter.Singleton,*/
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    // internal class NameConverter : JsonConverter
    // {
    //     public override bool CanConvert(Type t) => t == typeof(Name) || t == typeof(Name?);

    //     public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
    //     {
    //         if (reader.TokenType == JsonToken.Null) return null;
    //         var value = serializer.Deserialize<string>(reader);
    //         if (value == "Untitled")
    //         {
    //             return Name.Untitled;
    //         }
    //         throw new Exception("Cannot unmarshal type Name");
    //     }

    //     public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
    //     {
    //         if (untypedValue == null)
    //         {
    //             serializer.Serialize(writer, null);
    //             return;
    //         }
    //         var value = (Name)untypedValue;
    //         if (value == Name.Untitled)
    //         {
    //             serializer.Serialize(writer, "Untitled");
    //             return;
    //         }
    //         throw new Exception("Cannot marshal type Name");
    //     }

    //     public static readonly NameConverter Singleton = new NameConverter();
    // }

    // internal class TextureConverter : JsonConverter
    // {
    //     public override bool CanConvert(Type t) => t == typeof(Texture) || t == typeof(Texture?);

    //     public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
    //     {
    //         if (reader.TokenType == JsonToken.Null) return null;
    //         var value = serializer.Deserialize<string>(reader);
    //         if (value == "line.png")
    //         {
    //             return Texture.LinePng;
    //         }
    //         throw new Exception("Cannot unmarshal type Texture");
    //     }

    //     public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
    //     {
    //         if (untypedValue == null)
    //         {
    //             serializer.Serialize(writer, null);
    //             return;
    //         }
    //         var value = (Texture)untypedValue;
    //         if (value == Texture.LinePng)
    //         {
    //             serializer.Serialize(writer, "line.png");
    //             return;
    //         }
    //         throw new Exception("Cannot marshal type Texture");
    //     }

    //     public static readonly TextureConverter Singleton = new TextureConverter();
    // }

    
}

